#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "the pre-commit hook ran 🚀"

npm run check-format ||
(
    echo 'Prettier formatting failed. Formatting files'
    
)

# Check ESLint Standards
npm run lint ||
(
        echo 'ESlint checked failed. Please try again!'
        false; 
)


# Check tsconfig standards
npm run check-types ||
(
    echo 'Type checks failed. Please try again!'
    false;
)
#Ignore fund messge
npm config set fund false 
# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

npm run build ||
(
    echo 'Build failed. Please try again'
    false;
)

npm run add-build || {
    echo 'Failed adding build. Please try again'
}

# If everything passes... Now we can commit
echo 'Everything looks good! Committing changes!'
