name: Check Japan-dev.com For New Jobs
on:
  schedule:
    - cron: "0 */6 * * *"
    - cron: "0 1 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Check for jobs on Japan-dev.com
        run: |
          curl --request POST \
          --url 'https://japandev-jobs-notion.vercel.app/api/jobs/create' \
      - name: Delete Jobs from Xata Database
        run: |
          curl --request DELETE \
          --url 'https://japandev-jobs-notion.vercel.app/api/jobs/delete' \
