name: daily-cron
on:
  schedule:
    - cron: "0 00 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Check for jobs on Japan-dev.com
        run: |
          curl --request GET \
          --url 'https://tokyo-jobs-notion.vercel.app/' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
